server {
  listen 80;

  # Serve React app
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri /index.html;
  }

  # 🔥 Proxy API calls to backend
  location /incidents {
    proxy_pass http://backend:3000/incidents;
  }

  location /workitem {
    proxy_pass http://backend:3000/workitem;
  }
}
