version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ims
      POSTGRES_PASSWORD: ims
      POSTGRES_DB: ims_db
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"