const fs = require("fs");
const path = require("path");

const SOURCE_FILE = path.join(
  __dirname,
  "../src/api/audit.routes.js"
);

const OUTPUT_FILE = path.join(
  __dirname,
  "../docs/reference/audit-api.md"
);

const source = fs.readFileSync(SOURCE_FILE, "utf8");

function parseDocumentation(source) {
  const blocks = [];

  const regex = /\/\*\*([\s\S]*?)\*\/\s*router\.(get|post|put|patch|delete)\(["']([^"']+)["']/g;

  let match;

  while ((match = regex.exec(source)) !== null) {
    const comment = match[1];
    const method = match[2].toUpperCase();
    const route = match[3];

    const lines = comment
      .split("\n")
      .map(line => line.replace(/^\s*\*\s?/, "").trim())
      .filter(Boolean);

    const doc = {
      method,
      route,
      docId: null,
      description: "",
      body: [],
      query: [],
      responses: []
    };

    for (const line of lines) {
      if (line.startsWith("@docId")) {
        doc.docId = line.replace("@docId", "").trim();
      }

      else if (line.startsWith("@description")) {
        doc.description = line
          .replace("@description", "")
          .trim();
      }

      else if (line.startsWith("@body")) {
        const value = line.replace("@body", "").trim();

        const parts = value.split(/\s+/);

        doc.body.push({
          name: parts[0],
          type: parts[1],
          required: parts[2] === "required",
          description: parts.slice(3).join(" ")
        });
      }

      else if (line.startsWith("@query")) {
        const value = line.replace("@query", "").trim();

        const parts = value.split(/\s+/);

        doc.query.push({
          name: parts[0],
          type: parts[1],
          required: parts[2] === "required",
          description: parts.slice(3).join(" ")
        });
      }

      else if (line.startsWith("@response")) {
        const value = line.replace("@response", "").trim();

        const parts = value.split(/\s+/);

        doc.responses.push({
          status: parts[0],
          description: parts.slice(1).join(" ")
        });
      }
    }

    blocks.push(doc);
  }

  return blocks;
}

function generateMdx(docs) {
  let output = `---
title: Audit API
generated: true
source: backend/src/api/audit.routes.js
generator: docs-as-code-demo
---

# Audit API

The Audit API provides endpoints for recording and retrieving
audit events generated by the Incident Management System.

`;

  for (const doc of docs) {
    output += `## ${doc.method} ${doc.route}

`;

    output += `**Documentation ID:** \`${doc.docId}\`

`;

    output += `${doc.description}

`;

    if (doc.body.length > 0) {
      output += `### Request Body

`;

      output += `| Field | Type | Required | Description |
|---|---|---|---|
`;

      for (const field of doc.body) {
        output += `| \`${field.name}\` | \`${field.type}\` | ${field.required ? "Yes" : "No"} | ${field.description} |
`;
      }

      output += "\n";
    }

    if (doc.query.length > 0) {
      output += `### Query Parameters

`;

      output += `| Parameter | Type | Required | Description |
|---|---|---|---|
`;

      for (const field of doc.query) {
        output += `| \`${field.name}\` | \`${field.type}\` | ${field.required ? "Yes" : "No"} | ${field.description} |
`;
      }

      output += "\n";
    }

    if (doc.responses.length > 0) {
      output += `### Responses

`;

      output += `| Status | Description |
|---|---|
`;

      for (const response of doc.responses) {
        output += `| \`${response.status}\` | ${response.description} |
`;
      }

      output += "\n";
    }
  }

  return output;
}

const docs = parseDocumentation(source);
const mdx = generateMdx(docs);

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });

fs.writeFileSync(OUTPUT_FILE, mdx);

console.log(
  `Generated ${docs.length} documentation entries → ${OUTPUT_FILE}`
);